### ISSUE TITLE
Publish package on WP registry

### ISSUE THREAD

**Issue by mattbucci** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#34]
Now that the old plugin has been removed from the WP registry I'm wondering if we can get this plugin published their instead and assume ownership over that community

**Comment by mattbucci** [comment]
Doesn't look like we can assume ownership, but it's possible to get it hosted there

**Comment by mattbucci** [comment]
It's likely we should resolve this before publishing: https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/issues/32

As of now it complains that we don't conform to plugin norms and list things like plugin name, etc

**Comment by mattbucci** [comment]
Once published we can create a github workflow to keep wordpress registry up to date when new releases are tagged.

```
name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"
    
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

- name: WordPress Plugin Deploy
  uses: 10up/action-wordpress-plugin-deploy@master
  env:
    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
```
